# https://docs.github.com/en/actions/quickstart
name: test cfengine-apt module
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - run: sudo apt update -qy && sudo apt install -qy python3-pip && pip3 install cfbs
      - run: ci/docker.sh
      - name: Test Summary
        uses: test-summary/action@v2
        with:
          paths: "out/masterfiles/**/test-*.xml"
        if: always()
