# https://docs.github.com/en/actions/quickstart
name: test cfengine-apt module
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - run: sudo apt update -qy && sudo apt install -qy python3-pip && pip3 install cfbs
      - run: ci/docker.sh
      - run: |
        ls -l | grep out
        ls -l out | grep masterfiles
        ls -l out/masterfiles | grep services
        ls -l out/masterfiles/services | grep cfbs
        ls -l out/masterfiles/services/cfbs | grep tests
        ls -l out/masterfiles/services/cfbs/tests/pin-packages
      - name: Test Summary
        uses: test-summary/action@v2
        with:
          paths: "./**/test-*.xml"
        if: always()
